/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void appCheckGreetingMessage() {
        App classUnderTest = new App();
        assertEquals("Ola mundo!", classUnderTest.getGreeting(), "mensagens não batem!");
    }
}
